version: '3.8'

services:
  mysql:
    container_name: mysql-sqlalchemy
    image: mysql:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

